const std = @import("std");
const tz = @import("tz");
const tg = tz.types;
const f = tz.functions;
const h = tz.helpers;

var g_environ: std.process.Environ = .empty;

fn isAllowed(msg: tg.Message_) bool {
    const env = g_environ.getPosix("TZ_OWNER_ID") orelse return true;
    const owner_id = std.fmt.parseInt(i64, env, 10) catch return true;
    return switch (msg.peer_id) {
        .PeerUser => |p| p.user_id == owner_id,
        else => false,
    };
}

fn replyMsgId(msg: tg.Message_) ?i32 {
    const rt = msg.reply_to.value orelse return null;
    return switch (rt) {
        .MessageReplyHeader => |rh| rh.reply_to_msg_id.value,
        else => null,
    };
}

fn msgPeer(ctx: h.Context, update: tg.UpdateNewMessage) ?struct { msg: tg.Message_, peer: tg.InputPeer } {
    const msg = switch (update.message) {
        .Message => |m| m,
        else => return null,
    };
    const peer = h.peerFromMessage(ctx.entities, msg) orelse return null;
    return .{ .msg = msg, .peer = peer };
}

// --- command handlers ---

fn onHelp(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    var ft = h.FormattedText.init(ctx.allocator);
    defer ft.deinit();
    try ft.bold("pill");
    try ft.plain(" — tz feature test\n\n");
    try ft.code("/echo <text>");
    try ft.plain(" echo in bold\n");
    try ft.code("/fmt");
    try ft.plain(" formatting demo\n");
    try ft.code("/keyboard");
    try ft.plain(" inline keyboard\n");
    try ft.code("/document");
    try ft.plain(" send a file\n");
    try ft.code("/info");
    try ft.plain(" your user info\n");
    try ft.code("/react");
    try ft.plain(" add ❤ (reply to msg)\n");
    try ft.code("/unreact");
    try ft.plain(" clear reactions (reply to msg)\n");
    try ft.code("/pin");
    try ft.plain(" pin a message (reply to msg)\n");
    try ft.code("/unpin");
    try ft.plain(" unpin a message (reply to msg)\n");
    try ft.code("/forward");
    try ft.plain(" forward to this chat (reply to msg)\n");
    try ft.plain("\nSend me a photo and I'll download and re-send it.");
    try h.reply(ctx, update, ft.text.items, .{ .entities = ft.entities.items });
}

fn onEcho(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const msg = switch (update.message) {
        .Message => |m| m,
        else => return,
    };
    const arg = msg.message["/echo ".len..];
    var ft = h.FormattedText.init(ctx.allocator);
    defer ft.deinit();
    try ft.bold(arg);
    try h.reply(ctx, update, ft.text.items, .{ .entities = ft.entities.items });
}

fn onFmt(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    var ft = h.FormattedText.init(ctx.allocator);
    defer ft.deinit();
    try ft.bold("bold");
    try ft.plain("  ");
    try ft.italic("italic");
    try ft.plain("  ");
    try ft.underline("underline");
    try ft.plain("  ");
    try ft.strike("strike");
    try ft.plain("  ");
    try ft.spoiler("spoiler");
    try ft.plain("\n");
    try ft.code("inline code");
    try ft.plain("\n");
    try ft.pre("pub fn main() !void {}\n", "zig");
    try ft.link("ziglang.org", "https://ziglang.org");
    try h.reply(ctx, update, ft.text.items, .{ .entities = ft.entities.items });
}

fn onKeyboard(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const mp = msgPeer(ctx, update) orelse return;
    var row1 = [_]tg.KeyboardButton{
        h.callbackButton("Button A", "cb:a"),
        h.callbackButton("Button B", "cb:b"),
    };
    var row2 = [_]tg.KeyboardButton{
        h.urlButton("ziglang.org", "https://ziglang.org"),
    };
    var rows = [_]tg.KeyboardButtonRow{
        h.inlineRow(&row1),
        h.inlineRow(&row2),
    };
    _ = try ctx.call(f.messages.SendMessage{
        .peer = mp.peer,
        .message = "Choose:",
        .reply_markup = .some(h.inlineKeyboard(&rows)),
    });
}

fn onDocument(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const data = "pill bot — test document\ngenerated by tz\n";
    try h.sendDocument(ctx, update, data, "text/plain", .{ .caption = "pill.txt" });
}

fn onInfo(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const msg = switch (update.message) {
        .Message => |m| m,
        else => return,
    };
    const sender_id = blk: {
        if (msg.from_id.value) |from| {
            if (from == .PeerUser) break :blk from.PeerUser.user_id;
        }
        if (msg.peer_id == .PeerUser) break :blk msg.peer_id.PeerUser.user_id;
        return;
    };
    const access_hash = ctx.entities.accessHash(sender_id) orelse return;
    var id_input = [_]tg.InputUser{.{ .InputUser = .{ .user_id = sender_id, .access_hash = access_hash } }};
    const users = try ctx.call(f.users.GetUsers{ .id = &id_input });
    defer ctx.allocator.free(users);

    if (users.len == 0) {
        try h.reply(ctx, update, "no result", .{});
        return;
    }
    const user = switch (users[0]) {
        .User => |u| u,
        else => {
            try h.reply(ctx, update, "unexpected user type", .{});
            return;
        },
    };

    var ft = h.FormattedText.init(ctx.allocator);
    defer ft.deinit();
    try ft.bold("User info\n");

    const id_str = try std.fmt.allocPrint(ctx.allocator, "id: {d}\n", .{user.id});
    defer ctx.allocator.free(id_str);
    try ft.plain(id_str);

    if (user.first_name.value) |name| {
        try ft.plain("first: ");
        try ft.plain(name);
        try ft.plain("\n");
    }
    if (user.last_name.value) |name| {
        try ft.plain("last: ");
        try ft.plain(name);
        try ft.plain("\n");
    }
    if (user.username.value) |name| {
        try ft.plain("username: @");
        try ft.plain(name);
        try ft.plain("\n");
    }
    if (user.bot.value != null) try ft.italic("(bot account)");

    try h.reply(ctx, update, ft.text.items, .{ .entities = ft.entities.items });
}

fn onReact(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const mp = msgPeer(ctx, update) orelse return;
    const target_id = replyMsgId(mp.msg) orelse mp.msg.id;
    try h.addReaction(ctx, mp.peer, target_id, "❤");
}

fn onUnreact(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const mp = msgPeer(ctx, update) orelse return;
    const target_id = replyMsgId(mp.msg) orelse mp.msg.id;
    try h.removeReaction(ctx, mp.peer, target_id);
}

fn onPin(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const mp = msgPeer(ctx, update) orelse return;
    const target_id = replyMsgId(mp.msg) orelse {
        try h.reply(ctx, update, "Reply to a message to pin it.", .{});
        return;
    };
    try h.pinMessage(ctx, mp.peer, target_id, .{});
}

fn onUnpin(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const mp = msgPeer(ctx, update) orelse return;
    const target_id = replyMsgId(mp.msg) orelse {
        try h.reply(ctx, update, "Reply to a message to unpin it.", .{});
        return;
    };
    try h.pinMessage(ctx, mp.peer, target_id, .{ .unpin = true });
}

fn onForward(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const mp = msgPeer(ctx, update) orelse return;
    const target_id = replyMsgId(mp.msg) orelse {
        try h.reply(ctx, update, "Reply to a message to forward it.", .{});
        return;
    };
    var fwd_ids = [_]i32{target_id};
    try h.forwardMessages(ctx, mp.peer, mp.peer, &fwd_ids);
}

fn stickerFilename(doc: tg.Document_) []const u8 {
    for (doc.attributes) |attr| {
        switch (attr) {
            .DocumentAttributeFilename => |a| return a.file_name,
            else => {},
        }
    }
    if (std.mem.eql(u8, doc.mime_type, "video/webm")) return "sticker.webm";
    if (std.mem.eql(u8, doc.mime_type, "application/x-tgsticker")) return "sticker.tgs";
    return "sticker.webp";
}

// --- update handlers ---

const R = h.Cmd(tg.UpdateNewMessage);

fn onMessage(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const msg = switch (update.message) {
        .Message => |m| m,
        else => return,
    };
    if (!isAllowed(msg)) return;

    if (try h.route(ctx, update, msg.message, &.{
        R.exact("/start", onHelp),
        R.exact("/help", onHelp),
        R.prefix("/echo ", onEcho),
        R.exact("/fmt", onFmt),
        R.exact("/keyboard", onKeyboard),
        R.exact("/document", onDocument),
        R.exact("/info", onInfo),
        R.exact("/react", onReact),
        R.exact("/unreact", onUnreact),
        R.exact("/pin", onPin),
        R.exact("/unpin", onUnpin),
        R.exact("/forward", onForward),
    })) return;

    const media = msg.media.value orelse return;
    switch (media) {
        .MessageMediaPhoto => |mp| {
            const photo = switch (mp.photo.value orelse return) {
                .Photo => |p| p,
                else => return,
            };
            const location = h.photoLocation(.{ .Photo = photo }) orelse return;
            const bytes = try h.download(ctx, location);
            defer ctx.allocator.free(bytes);
            try h.sendDocument(ctx, update, bytes, "image/jpeg", .{ .caption = "re-sent photo" });
        },
        .MessageMediaDocument => |md| {
            const doc_union = md.document.value orelse return;
            const doc = switch (doc_union) {
                .Document => |d| d,
                else => return,
            };
            const is_sticker = for (doc.attributes) |attr| {
                if (attr == .DocumentAttributeSticker) break true;
            } else false;
            if (!is_sticker) return;
            const location = h.documentLocation(doc_union) orelse return;
            const bytes = try h.download(ctx, location);
            defer ctx.allocator.free(bytes);
            try h.sendDocument(ctx, update, bytes, doc.mime_type, .{ .caption = stickerFilename(doc) });
        },
        else => {},
    }
}

fn onCallback(ctx: h.Context, update: tg.UpdateBotCallbackQuery) !void {
    const data = update.data.value orelse return;
    if (std.mem.eql(u8, data, "cb:a")) {
        try h.answerCallbackQuery(ctx, update, .{ .text = "You pressed A!" });
    } else if (std.mem.eql(u8, data, "cb:b")) {
        try h.answerCallbackQuery(ctx, update, .{ .text = "You pressed B!", .alert = true });
    } else {
        try h.answerCallbackQuery(ctx, update, .{});
    }
}

const handlers = &.{
    tz.handler(tg.UpdateNewMessage, onMessage),
    tz.handler(tg.UpdateBotCallbackQuery, onCallback),
};

pub fn main(init: std.process.Init.Minimal) !void {
    g_environ = init.environ;

    const allocator = std.heap.smp_allocator;

    var threaded = std.Io.Threaded.init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();

    var file_storage = tz.storage.FileStorage.init("pill.session");

    const client = try tz.Client(handlers).init(allocator, .{
        .api_id = try std.fmt.parseInt(i32, init.environ.getPosix("TZ_API_ID") orelse usage(), 10),
        .api_hash = init.environ.getPosix("TZ_API_HASH") orelse usage(),
        .bot_token = init.environ.getPosix("TZ_BOT_TOKEN") orelse usage(),
        .storage = file_storage.storage(),
    });
    defer client.deinit();

    try client.run(io);
}

fn usage() noreturn {
    std.log.err("usage: TZ_API_ID=<id> TZ_API_HASH=<hash> TZ_BOT_TOKEN=<token> ./feature_demo", .{});
    std.process.exit(1);
}
