const std = @import("std");
const tz = @import("tz");
const tg = tz.types;
const f = tz.functions;
const h = tz.helpers;

const owner_id: i64 = 30000000;

fn isOwner(msg: tg.Message_) bool {
    return switch (msg.peer_id) {
        .PeerUser => |p| p.user_id == owner_id,
        else => false,
    };
}

fn replyMsgId(msg: tg.Message_) ?i32 {
    const rt = msg.reply_to.value orelse return null;
    return switch (rt) {
        .MessageReplyHeader => |rh| rh.reply_to_msg_id.value,
        else => null,
    };
}

fn onMessage(ctx: h.Context, update: tg.UpdateNewMessage) !void {
    const msg = switch (update.message) {
        .Message => |m| m,
        else => return,
    };
    if (!isOwner(msg)) return;

    const text = msg.message;
    const peer = h.peerFromMessage(ctx.entities, msg) orelse return;

    if (std.mem.eql(u8, text, "/start") or std.mem.eql(u8, text, "/help")) {
        var ft = h.FormattedText.init(ctx.allocator);
        defer ft.deinit();
        try ft.bold("pill");
        try ft.plain(" — tz feature test\n\n");
        try ft.code("/echo <text>");
        try ft.plain(" echo in bold\n");
        try ft.code("/fmt");
        try ft.plain(" formatting demo\n");
        try ft.code("/keyboard");
        try ft.plain(" inline keyboard\n");
        try ft.code("/document");
        try ft.plain(" send a file\n");
        try ft.code("/album");
        try ft.plain(" send a document album\n");
        try ft.code("/info");
        try ft.plain(" your user info\n");
        try ft.code("/react");
        try ft.plain(" add 👍 (reply to msg)\n");
        try ft.code("/unreact");
        try ft.plain(" clear reactions (reply to msg)\n");
        try ft.code("/pin");
        try ft.plain(" pin a message (reply to msg)\n");
        try ft.code("/unpin");
        try ft.plain(" unpin a message (reply to msg)\n");
        try ft.code("/forward");
        try ft.plain(" forward to this chat (reply to msg)\n");
        try ft.plain("\nSend me a photo and I'll download and re-send it.");
        try h.reply(ctx, update, ft.text.items, .{ .entities = ft.entities.items });
        return;
    }

    if (std.mem.startsWith(u8, text, "/echo ")) {
        const arg = text["/echo ".len..];
        var ft = h.FormattedText.init(ctx.allocator);
        defer ft.deinit();
        try ft.bold(arg);
        try h.reply(ctx, update, ft.text.items, .{ .entities = ft.entities.items });
        return;
    }

    if (std.mem.eql(u8, text, "/fmt")) {
        var ft = h.FormattedText.init(ctx.allocator);
        defer ft.deinit();
        try ft.bold("bold");
        try ft.plain("  ");
        try ft.italic("italic");
        try ft.plain("  ");
        try ft.underline("underline");
        try ft.plain("  ");
        try ft.strike("strike");
        try ft.plain("  ");
        try ft.spoiler("spoiler");
        try ft.plain("\n");
        try ft.code("inline code");
        try ft.plain("\n");
        try ft.pre("pub fn main() !void {}\n", "zig");
        try ft.link("ziglang.org", "https://ziglang.org");
        try h.reply(ctx, update, ft.text.items, .{ .entities = ft.entities.items });
        return;
    }

    if (std.mem.eql(u8, text, "/keyboard")) {
        var row1 = [_]tg.KeyboardButton{
            h.callbackButton("Button A", "cb:a"),
            h.callbackButton("Button B", "cb:b"),
        };
        var row2 = [_]tg.KeyboardButton{
            h.urlButton("ziglang.org", "https://ziglang.org"),
        };
        var rows = [_]tg.KeyboardButtonRow{
            h.inlineRow(&row1),
            h.inlineRow(&row2),
        };
        _ = try ctx.call(f.messages.SendMessage{
            .peer = peer,
            .message = "Choose:",
            .reply_markup = .some(h.inlineKeyboard(&rows)),
        });
        return;
    }

    if (std.mem.eql(u8, text, "/document")) {
        const data = "pill bot — test document\ngenerated by tz\n";
        try h.sendDocument(ctx, update, data, "text/plain", .{ .caption = "pill.txt" });
        return;
    }

    if (std.mem.eql(u8, text, "/album")) {
        const items = &[_]h.AlbumItem{
            .{
                .data = "first file in album\n",
                .caption = "one",
                .name = "one.txt",
                .kind = .document,
                .mime_type = "text/plain",
            },
            .{
                .data = "second file in album\n",
                .caption = "two",
                .name = "two.txt",
                .kind = .document,
                .mime_type = "text/plain",
            },
        };
        try h.sendAlbum(ctx, update, items, .{});
        return;
    }

    if (std.mem.eql(u8, text, "/info")) {
        var id_input = [_]tg.InputUser{.{ .InputUserSelf = .{} }};
        const users = try ctx.call(f.users.GetUsers{ .id = &id_input });
        defer ctx.allocator.free(users);

        if (users.len == 0) {
            try h.reply(ctx, update, "no result", .{});
            return;
        }
        const user = switch (users[0]) {
            .User => |u| u,
            else => {
                try h.reply(ctx, update, "unexpected user type", .{});
                return;
            },
        };

        var ft = h.FormattedText.init(ctx.allocator);
        defer ft.deinit();
        try ft.bold("User info\n");

        const id_str = try std.fmt.allocPrint(ctx.allocator, "id: {d}\n", .{user.id});
        defer ctx.allocator.free(id_str);
        try ft.plain(id_str);

        if (user.first_name.value) |name| {
            try ft.plain("first: ");
            try ft.plain(name);
            try ft.plain("\n");
        }
        if (user.last_name.value) |name| {
            try ft.plain("last: ");
            try ft.plain(name);
            try ft.plain("\n");
        }
        if (user.username.value) |name| {
            try ft.plain("username: @");
            try ft.plain(name);
            try ft.plain("\n");
        }
        if (user.bot.value != null) {
            try ft.italic("(bot account)");
        }

        try h.reply(ctx, update, ft.text.items, .{ .entities = ft.entities.items });
        return;
    }

    if (std.mem.eql(u8, text, "/react")) {
        const target_id = replyMsgId(msg) orelse msg.id;
        try h.addReaction(ctx, peer, target_id, "👍");
        return;
    }

    if (std.mem.eql(u8, text, "/unreact")) {
        const target_id = replyMsgId(msg) orelse msg.id;
        try h.removeReaction(ctx, peer, target_id);
        return;
    }

    if (std.mem.eql(u8, text, "/pin")) {
        const target_id = replyMsgId(msg) orelse {
            try h.reply(ctx, update, "Reply to a message to pin it.", .{});
            return;
        };
        try h.pinMessage(ctx, peer, target_id, .{});
        return;
    }

    if (std.mem.eql(u8, text, "/unpin")) {
        const target_id = replyMsgId(msg) orelse {
            try h.reply(ctx, update, "Reply to a message to unpin it.", .{});
            return;
        };
        try h.pinMessage(ctx, peer, target_id, .{ .unpin = true });
        return;
    }

    if (std.mem.eql(u8, text, "/forward")) {
        const target_id = replyMsgId(msg) orelse {
            try h.reply(ctx, update, "Reply to a message to forward it.", .{});
            return;
        };
        var fwd_ids = [_]i32{target_id};
        try h.forwardMessages(ctx, peer, peer, &fwd_ids);
        return;
    }

    // If the message has a photo, download it and re-send as document.
    const media = msg.media.value orelse return;
    switch (media) {
        .MessageMediaPhoto => |mp| {
            const photo = switch (mp.photo.value orelse return) {
                .Photo => |p| p,
                else => return,
            };
            const location = h.photoLocation(.{ .Photo = photo }) orelse return;
            const bytes = try h.download(ctx, location);
            defer ctx.allocator.free(bytes);
            try h.sendDocument(ctx, update, bytes, "image/jpeg", .{ .caption = "re-sent photo" });
        },
        else => {},
    }
}

fn onCallback(ctx: h.Context, update: tg.UpdateBotCallbackQuery) !void {
    const data = update.data.value orelse return;
    if (std.mem.eql(u8, data, "cb:a")) {
        try h.answerCallbackQuery(ctx, update, .{ .text = "You pressed A!" });
    } else if (std.mem.eql(u8, data, "cb:b")) {
        try h.answerCallbackQuery(ctx, update, .{ .text = "You pressed B!", .alert = true });
    } else {
        try h.answerCallbackQuery(ctx, update, .{});
    }
}

const handlers = &.{
    tz.handler(tg.UpdateNewMessage, onMessage),
    tz.handler(tg.UpdateBotCallbackQuery, onCallback),
};

pub fn main() !void {
    var gpa = std.heap.DebugAllocator(.{}){};
    defer _ = gpa.deinit();
    const allocator = gpa.allocator();

    var threaded = std.Io.Threaded.init(allocator, .{});
    defer threaded.deinit();
    const io = threaded.io();

    var file_storage = tz.FileStorage.init("pill.session");

    const client = try tz.Client(handlers).init(allocator, .{
        .api_id = try std.fmt.parseInt(i32, std.mem.span(std.c.getenv("TZ_API_ID") orelse usage()), 10),
        .api_hash = std.mem.span(std.c.getenv("TZ_API_HASH") orelse usage()),
        .bot_token = std.mem.span(std.c.getenv("TZ_BOT_TOKEN") orelse usage()),
        .storage = file_storage.storage(),
    });
    defer client.deinit();

    try client.run(io);
}

fn usage() noreturn {
    std.log.err("usage: TZ_API_ID=<id> TZ_API_HASH=<hash> TZ_BOT_TOKEN=<token> ./pill", .{});
    std.process.exit(1);
}
